// User Roles

const USER_ROLES = {
  SUPERADMIN: "SUPERADMIN",
  CLIENT: "CLIENT",
  MAINTAINER: "MAINTAINER",
  JANITOR: "JANITOR",
  TENANT: "TENANT",
  PROVIDER: "PROVIDER",
};

// User Status
const USER_STATUS = {
  NEW: "NEW",
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  DELETED: "DELETED",
};

// User Permissions

const USER_PERMISSIONS = {
  READ_MAINTENANCE: "READ_MAINTENANCE",
  UPDATE_MAINTENANCE: "UPDATE_MAINTENANCE",

  READ_MESSAGE: "READ_MESSAGE",
  UPDATE_MESSAGE: "UPDATE_MESSAGE",

  READ_NOTICE: "READ_NOTICE",
  UPDATE_NOTICE: "UPDATE_NOTICE",

  READ_BILL: "READ_BILL",
  UPDATE_BILL: "UPDATE_BILL",

  READ_PROPERTY: "READ_PROPERTY",
  UPDATE_PROPERTY: "UPDATE_PROPERTY",

  READ_TENANT: "READ_TENANT",
  UPDATE_TENANT: "UPDATE_TENANT",

  READ_FINANCE: "READ_FINANCE",
  READ_REPORT: "READ_REPORT",
};

const USER_NOTIFICATIONS = {
  MAINTENANCE_NOTIFICATION: "MAINTENANCE_NOTIFICATION",
};

const PROPERTY_TYPE = {
  APARTMENT: "apartment",
  OFFICE_BUILDING: "office_building",
  HOUSE: "house",
  WAREHOUSE: "warehouse",
};

// Maintenance Status
const MAINTENANCE_STATUS = {
  PENDING: "PENDING",
  INPROGRESS: "INPROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

const SERVICE_TYPES = {
  CLEANING: "CLEANING",
  PLUMBING: "PLUMBING",
  ELECTRICIAN: "ELECTRICIAN",
  CARPENTRY: "CARPENTRY",
  PAINTING: "PAINTING",
};

// Coupon Types

const COUPON_TYPES = {
  FIXED: "FIXED",
  PERCENTAGE: "PERCENTAGE",
  TEST: "TEST",
};

module.exports = {
  USER_ROLES,
  USER_STATUS,
  USER_PERMISSIONS,
  USER_NOTIFICATIONS,
  PROPERTY_TYPE,
  MAINTENANCE_STATUS,
  SERVICE_TYPES,
  COUPON_TYPES,
};
