// User Roles

const USER_ROLES = {
  SUPERADMIN: "SUPERADMIN",
  CLIENT: "CLIENT",
  MANAGER: "MANAGER",
  MAINTAINER: "MAINTAINER",
  JANITOR: "JANITOR",
  TENANT: "TENANT",
};

// User Status
const USER_STATUS = {
  NEW: "NEW",
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  DELETED: "DELETED",
};

// User Permissions

const USER_PERMISSIONS = {
  READ_MAINTENANCE: "READ_MAINTENANCE",
  UPDATE_MAINTENANCE: "UPDATE_MAINTENANCE",
  DELETE_MAINTENANCE: "DELETE_MAINTENANCE",

  CREATE_MAINTAINER: "CREATE_MAINTAINER",
  READ_MAINTAINER: "READ_MAINTAINER",
  UPDATE_MAINTAINER: "UPDATE_MAINTAINER",
  DELETE_MAINTAINER: "DELETE_MAINTAINER",

  CREATE_JANITOR: "CREATE_JANITOR",
  READ_JANITOR: "READ_JANITOR",
  UPDATE_JANITOR: "UPDATE_JANITOR",
  DELETE_JANITOR: "DELETE_JANITOR",

  CREATE_TENANT: "CREATE_TENANT",
  READ_TENANT: "READ_TENANT",
  UPDATE_TENANT: "UPDATE_TENANT",
  DELETE_TENANT: "DELETE_TENANT",

  READ_FINANCE: "READ_FINANCE",
  READ_REPORTS: "READ_REPORTS",
};

const PROPERTY_TYPE = {
  APARTMENT: "apartment",
  OFFICE_BUILDING: "office_building",
  HOUSE: "house",
  WAREHOUSE: "warehouse",
};

// Maintenance Status
const MAINTENANCE_STATUS = {
  PENDING: "PENDING",
  INPROGRESS: "INPROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

// Coupon Types

const COUPON_TYPES = {
  FIXED: "FIXED",
  PERCENTAGE: "PERCENTAGE",
  TEST: "TEST",
};

module.exports = {
  USER_ROLES,
  USER_STATUS,
  USER_PERMISSIONS,
  PROPERTY_TYPE,
  MAINTENANCE_STATUS,
  COUPON_TYPES,
};
